# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_plaform_details.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_plaform_details.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19get_plaform_details.proto\"0\n\x19GetPlatformDetailsRequest\x12\x13\n\x0bmpf_version\x18\x01 \x01(\t\"\xf8\x01\n\x1aGetPlatformDetailsResponse\x12i\n!known_switches_with_initial_state\x18\x01 \x03(\x0b\x32>.GetPlatformDetailsResponse.KnownSwitchesWithInitialStateEntry\x12\x14\n\x0cknown_lights\x18\x02 \x03(\t\x12\x13\n\x0bknown_coils\x18\x03 \x03(\t\x1a\x44\n\"KnownSwitchesWithInitialStateEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x62\x06proto3'
)




_GETPLATFORMDETAILSREQUEST = _descriptor.Descriptor(
  name='GetPlatformDetailsRequest',
  full_name='GetPlatformDetailsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mpf_version', full_name='GetPlatformDetailsRequest.mpf_version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=77,
)


_GETPLATFORMDETAILSRESPONSE_KNOWNSWITCHESWITHINITIALSTATEENTRY = _descriptor.Descriptor(
  name='KnownSwitchesWithInitialStateEntry',
  full_name='GetPlatformDetailsResponse.KnownSwitchesWithInitialStateEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='GetPlatformDetailsResponse.KnownSwitchesWithInitialStateEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='GetPlatformDetailsResponse.KnownSwitchesWithInitialStateEntry.value', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=328,
)

_GETPLATFORMDETAILSRESPONSE = _descriptor.Descriptor(
  name='GetPlatformDetailsResponse',
  full_name='GetPlatformDetailsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='known_switches_with_initial_state', full_name='GetPlatformDetailsResponse.known_switches_with_initial_state', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='known_lights', full_name='GetPlatformDetailsResponse.known_lights', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='known_coils', full_name='GetPlatformDetailsResponse.known_coils', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GETPLATFORMDETAILSRESPONSE_KNOWNSWITCHESWITHINITIALSTATEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=328,
)

_GETPLATFORMDETAILSRESPONSE_KNOWNSWITCHESWITHINITIALSTATEENTRY.containing_type = _GETPLATFORMDETAILSRESPONSE
_GETPLATFORMDETAILSRESPONSE.fields_by_name['known_switches_with_initial_state'].message_type = _GETPLATFORMDETAILSRESPONSE_KNOWNSWITCHESWITHINITIALSTATEENTRY
DESCRIPTOR.message_types_by_name['GetPlatformDetailsRequest'] = _GETPLATFORMDETAILSREQUEST
DESCRIPTOR.message_types_by_name['GetPlatformDetailsResponse'] = _GETPLATFORMDETAILSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetPlatformDetailsRequest = _reflection.GeneratedProtocolMessageType('GetPlatformDetailsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPLATFORMDETAILSREQUEST,
  '__module__' : 'get_plaform_details_pb2'
  # @@protoc_insertion_point(class_scope:GetPlatformDetailsRequest)
  })
_sym_db.RegisterMessage(GetPlatformDetailsRequest)

GetPlatformDetailsResponse = _reflection.GeneratedProtocolMessageType('GetPlatformDetailsResponse', (_message.Message,), {

  'KnownSwitchesWithInitialStateEntry' : _reflection.GeneratedProtocolMessageType('KnownSwitchesWithInitialStateEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETPLATFORMDETAILSRESPONSE_KNOWNSWITCHESWITHINITIALSTATEENTRY,
    '__module__' : 'get_plaform_details_pb2'
    # @@protoc_insertion_point(class_scope:GetPlatformDetailsResponse.KnownSwitchesWithInitialStateEntry)
    })
  ,
  'DESCRIPTOR' : _GETPLATFORMDETAILSRESPONSE,
  '__module__' : 'get_plaform_details_pb2'
  # @@protoc_insertion_point(class_scope:GetPlatformDetailsResponse)
  })
_sym_db.RegisterMessage(GetPlatformDetailsResponse)
_sym_db.RegisterMessage(GetPlatformDetailsResponse.KnownSwitchesWithInitialStateEntry)


_GETPLATFORMDETAILSRESPONSE_KNOWNSWITCHESWITHINITIALSTATEENTRY._options = None
# @@protoc_insertion_point(module_scope)
