# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: switch.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='switch.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cswitch.proto\"\x16\n\x14SwitchChangesRequest\"Q\n\rSwitchChanges\x12\x15\n\rswitch_number\x18\x01 \x01(\t\x12\x14\n\x0cswitch_state\x18\x02 \x01(\x08\x12\x13\n\x0b\x63hange_time\x18\x03 \x01(\x04\x62\x06proto3'
)




_SWITCHCHANGESREQUEST = _descriptor.Descriptor(
  name='SwitchChangesRequest',
  full_name='SwitchChangesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=38,
)


_SWITCHCHANGES = _descriptor.Descriptor(
  name='SwitchChanges',
  full_name='SwitchChanges',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='switch_number', full_name='SwitchChanges.switch_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='switch_state', full_name='SwitchChanges.switch_state', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='change_time', full_name='SwitchChanges.change_time', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['SwitchChangesRequest'] = _SWITCHCHANGESREQUEST
DESCRIPTOR.message_types_by_name['SwitchChanges'] = _SWITCHCHANGES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SwitchChangesRequest = _reflection.GeneratedProtocolMessageType('SwitchChangesRequest', (_message.Message,), {
  'DESCRIPTOR' : _SWITCHCHANGESREQUEST,
  '__module__' : 'switch_pb2'
  # @@protoc_insertion_point(class_scope:SwitchChangesRequest)
  })
_sym_db.RegisterMessage(SwitchChangesRequest)

SwitchChanges = _reflection.GeneratedProtocolMessageType('SwitchChanges', (_message.Message,), {
  'DESCRIPTOR' : _SWITCHCHANGES,
  '__module__' : 'switch_pb2'
  # @@protoc_insertion_point(class_scope:SwitchChanges)
  })
_sym_db.RegisterMessage(SwitchChanges)


# @@protoc_insertion_point(module_scope)
