strictness: veryhigh
max-line-length: 120

mccabe:
  options:
    max-complexity: 15

pyflakes:
  disable:
   - F401       # unused import. ignore until pyflakes supports type hints

doc-warnings: true

pep257:
   disable:
    - D211  # in conflict with D203
    - D213  # in conflict with D212
    - D406  # Section name should end with a newline
    - D407  # Missing dashed underline after section
    - D413  # Missing blank line after last section

pylint:
  disable:
    - pointless-string-statement  # pointless statement, which is how our event docstrings are seen
    - invalid-name  # we got ms and dt as defaults for a lot of functions
    - too-few-public-methods
    - cyclic-import     # remove when type checking is supported https://github.com/PyCQA/pylint/issues/647
    - unused-import     # remove when type checking is supported https://github.com/PyCQA/pylint/issues/647
    - no-else-return

  options:
    max-attributes: 12
    max-parents: 15
    max-branches: 15
    max-statements: 60
    max-public-methods: 40

ignore-paths:
  - docs
  - mpf/platforms/trinamics/
  - _mpf-mc                     # ignore mc in subpath on travis
