strictness: veryhigh
max-line-length: 120

mccabe:
  options:
    max-complexity: 20

pyflakes:
  disable:
   - F401       # unused import. ignore until pyflakes supports type hints

doc-warnings: true

pep257:
   disable:
    - D211  # in conflict with D203
    - D213  # in conflict with D212
    - D413  # Missing blank line after last section - need to fix a lot of docstrings first

pylint:
  disable:
    - pointless-string-statement  # pointless statement, which is how our event docstrings are seen
    - too-few-public-methods
    - unsubscriptable-object    # broken on python 3.9

  options:
    max-attributes: 12
    max-parents: 15
    max-branches: 30
    max-statements: 60
    max-public-methods: 40
    variable-rgx: "^[a-z_][a-z0-9]*((_[a-z0-9]+)*)?$"   # pep8 style but not more
    argument-rgx: "^[a-z_][a-z0-9]*((_[a-z0-9]+)*)?$"   # pep8 style but not more
    attr-rgx: "^[a-z_][a-z0-9_]*$"                      # pep8 style but not more
    method-rgx: "^[a-z_][a-z0-9_]*$"                    # pep8 style but not more

ignore-paths:
  - mpf/tests/
  - mpf/benchmarks/
  - docs
  - mpf/platforms/trinamics/
  - tools/
  - _mpf-mc                     # ignore mc in subpath on travis

ignore-patterns:
  - .*_pb2(_|\.).*
