strictness: high
max-line-length: 120

mccabe:
  options:
    max-complexity: 20

pyflakes:
  disable:
   - F401       # unused import. ignore until pyflakes supports type hints

doc-warnings: true

pep257:
  disable:
    - D211  # in conflict with D203
    - D213  # in conflict with D212
    # The following are disabled to make refactoring managable
    - D413  # Missing blank line after last section - need to fix a lot of docstrings first
    - D417  # Missing argument description in docstring

pylint:
  disable:
    - pointless-string-statement  # pointless statement, which is how our event docstrings are seen
    - too-few-public-methods
    - unsubscriptable-object    # broken on python 3.9
    # The following linter rules are disabled to make a refactor managable in chunks
    - consider-using-f-string  # temporarily disabling due to the 900+ instances to be replaced
    - useless-suppression  # disabling until all environments can agree on import paths
    - missing-class-docstring
    - use-dict-literal
    - use-list-literal
    - consider-using-max-builtin
    - consider-using-min-builtin
    - consider-using-generator
    - raise-missing-from

  options:
    logging-modules: logging
    logging-format-style: old
    max-attributes: 12
    max-parents: 15
    max-branches: 30
    max-statements: 60
    max-public-methods: 40
    variable-rgx: "^[a-z_][a-z0-9]*((_[a-z0-9]+)*)?$"   # pep8 style but not more
    argument-rgx: "^[a-z_][a-z0-9]*((_[a-z0-9]+)*)?$"   # pep8 style but not more
    attr-rgx: "^[a-z_][a-z0-9_]*$"                      # pep8 style but not more
    method-rgx: "^[a-z_][a-z0-9_]*$"                    # pep8 style but not more

ignore-paths:
  - mpf/tests/
  - mpf/benchmarks/
  - build
  - docs
  - mpf/platforms/trinamics/
  - mpf/platforms/visual_pinball_engine/
  - tools/
  - _mpf-mc                     # ignore mc in subpath on travis

ignore-patterns:
  - .*_pb2(_|\.).*
