# config_version=3
Config:
    - config.yaml

switch_player:
    start_event: machine_reset_phase_3
    start_delay: 1s
    steps:
      #- time: 100ms
      #  switch: s_trough_1
      #  action: activate
      
      # player 1 ball 1
      - time: 600ms
        switch: s_start
        action: hit
      - time: 100ms
        switch: s_trough_1
        action: deactivate
      - time: 1s
        switch: s_shooter_lane
        action: activate
      - time: 1s
        switch: s_ball_launch
        action: hit
      - time: 100ms
        switch: s_shooter_lane
        action: deactivate
      - time: 1s
        switch: s_upper_left_flipper_gate
        action: hit
      - time: 1s
        switch: s_left_loop
        action: hit
      - time: 1s
        switch: s_right_inlane
        action: hit
      - time: 500ms
        switch: s_start
        action: hit

      # Player 2 ball 1
      - time: 2.5s
        switch: s_trough_1
        action: activate
      - time: 1s
        switch: s_trough_1
        action: deactivate
      - time: 1s
        switch: s_shooter_lane
        action: activate
      - time: 1s
        switch: s_ball_launch
        action: hit
      - time: 100ms
        switch: s_shooter_lane
        action: deactivate
      - time: 200ms
        switch: s_right_inlane
        action: hit
      - time: 200ms
        switch: s_right_inlane
        action: hit
      - time: 200ms
        switch: s_right_inlane
        action: hit
      - time: 2.5s
        switch: s_trough_1
        action: activate

      # Player 1 ball 2
      - time: 2.5s
        switch: s_trough_1
        action: activate
      - time: 1s
        switch: s_trough_1
        action: deactivate
      - time: 1s
        switch: s_shooter_lane
        action: activate
      - time: 1s
        switch: s_ball_launch
        action: hit
      - time: 100ms
        switch: s_shooter_lane
        action: deactivate
      - time: 200ms
        switch: s_right_inlane
        action: hit

      # Player 2 ball 2
      - time: 2.5s
        switch: s_trough_1
        action: activate
      - time: 1s
        switch: s_trough_1
        action: deactivate
      - time: 1s
        switch: s_shooter_lane
        action: activate
      - time: 1s
        switch: s_ball_launch
        action: hit
      - time: 100ms
        switch: s_shooter_lane
        action: deactivate
      - time: 200ms
        switch: s_right_inlane
        action: hit

      # Player 1 ball 3
      - time: 2.5s
        switch: s_trough_1
        action: activate
      - time: 1s
        switch: s_trough_1
        action: deactivate
      - time: 1s
        switch: s_shooter_lane
        action: activate
      - time: 1s
        switch: s_ball_launch
        action: hit
      - time: 100ms
        switch: s_shooter_lane
        action: deactivate
      - time: 200ms
        switch: s_right_inlane
        action: hit
        
      # Player 2 ball 3
      - time: 2.5s
        switch: s_trough_1
        action: activate
      - time: 1s
        switch: s_trough_1
        action: deactivate
      - time: 1s
        switch: s_shooter_lane
        action: activate
      - time: 1s
        switch: s_ball_launch
        action: hit
      - time: 100ms
        switch: s_shooter_lane
        action: deactivate
      - time: 200ms
        switch: s_right_inlane
        action: hit

    # game end
      - time: 2.5s
        switch: s_trough_1
        action: activate
    
    # new game
      - time: 2s
        switch: s_start
        action: hit