# config_version=3

hardware:
  platform: smart_virtual
  driverboards: virtual

config:
    - hardware.yaml
    - shots.yaml
    - keyboard.yaml

mpf:
  default_pulse_ms: 20

game:
    balls_per_game: 3
    max_players: 4
#    player_controlled_eject_tag: plunger

modes:
  - base
  - claw_lit_for_major_mode
  - mode1_acmag
  - skillshot
  - bonus
  - high_score
  - tilt
#  - credits

scriptlets:
    add_a_ball.AddABall
    claw.Claw

images:
    demo_man_logo:
        target: dmd

#window:
#  width: 500
#  height: 300
#  minimum_width: 200
#  minimum_height: 100
#  borderless: false
#  fullscreen: false
#  rotation: 0
#  icon: None
#  title: Mission Pinball Framework
#  show_cursor: false
#  source_display: window
#  dpi: 96
#  scale_contents: true

displays:
  window:
    width: 400
    height: 300

screens:
  boot:
    type: text
    text: MPF BOOTY
#    x: 100
#    y: 100
#    pos: (100, 200)
#    size: (100, 50)