# config_version=3

config:
    - hardware.yaml

mpf:
  default_pulse_ms: 20

game:
    balls_per_game: 3
    max_players: 4
    player_controlled_eject_tag: plunger

modes:
  - base
  - claw_lit_for_major_mode
  - mode1_acmag
  - skillshot

scriptlets:
    attract.Attract
    add_a_ball.AddABall
    claw.Claw

slide_player:
    volume_change:
        type: Text
        text: "VOLUME: %display_volume"
        expire: 2s
        slide_priority: 10000
    assets_to_load:
        type: text
        text: "LOADING ASSETS: %assets TO GO"
        font: small
    assets_loading_complete:
        type: text
        text: ASSET LOADING COMPLETE
        font: small

images:
    demo_man_logo:
        target: dmd

