#config_version=3

# Config file for Step 11 of our step-by-step tutorial.
# https://missionpinball.com/docs/tutorial/

# WARNING: The switch and coil numbers in this configuration file are for a Demolition Man machine.
# Do not use this file with your own hardware unless you change the coil and switch numbers to match your actual
# hardware!

switches:
    s_left_flipper:
        number: SF4
    s_right_flipper:
        number: SF2
    s_trough1:
        number: s31
        label:
        tags:
        type: NC
    s_trough2:
        number: s32
        label:
        tags:
        type: NC
    s_trough3:
        number: s33
        label:
        tags:
        type: NC
    s_trough4:
        number: s34
        label:
        tags:
        type: NC
    s_trough5:
        number: s35
        label:
        tags:
        type: NC
    s_trough_jam:
        number: s36
        label:
        tags:
        type: NC
    s_plunger_lane:
        number: s27
    s_start:
        number: s13
        tags: start
    s_launch:
        number: s11
        tags: launch
    s_right_inlane:
        number: s17
        tags: playfield_active

coils:
    c_flipper_left_main: 
        number: FLLM
        pulse_ms: 25
    c_flipper_left_hold: 
        number: FLLH
    c_flipper_right_main: 
        number: FLRM
        pulse_ms: 25
    c_flipper_right_hold: 
        number: FLRH
    c_trough_eject:
        number: c01
        pulse_ms: 25
    c_plunger_eject:
        number: c03
        pulse_ms: 25

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper

dmd:
    physical: yes
    width: 128
    height: 32

window:
    elements:
      - type: virtualdmd
        width: 512
        height: 128
        h_pos: center
        v_pos: center
        pixel_color: ff6600
        dark_color: 220000
        pixel_spacing: 1
      - type: shape
        shape: box
        width: 516
        height: 132
        color: aaaaaa
        thickness: 2
      - type: text
        font: tall title
        text: MY AWESOME GAME
        h_pos: center
        v_pos: top
        y: 60
        size: 100
        antialias: yes
        layer: 1
        color: ee9900

slide_player:
    mode_attract_started:
        type: text
        text: PRESS START
        slide_priority: 10
    ball_started:
        type: text
        text: PLAYER %number% BALL %ball%
        slide_priority: 10

keyboard:
    z:
        switch: s_left_flipper
    /:
        switch: s_right_flipper
    1:
        switch: s_trough1
        toggle: true
    2:
        switch: s_trough2
        toggle: true
    3:
        switch: s_trough3
        toggle: true
    4:
        switch: s_trough4
        toggle: true
    5:
        switch: s_trough5
        toggle: true
    p:
        switch: s_plunger_lane
        toggle: true
    s:
        switch: s_start
    L:
        switch: s_launch
    q:
        switch: s_right_inlane

ball_devices:
  bd_trough:
    tags: trough, home, drain
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough_jam
    eject_coil: c_trough_eject
    entrance_count_delay: 300ms
    jam_switch: s_trough_jam
    eject_targets: bd_plunger
    debug: yes
  bd_plunger:
    ball_switches: s_plunger_lane
    entrance_count_delay: 300ms
    eject_timeouts: 3s
    tags: ball_add_live
    eject_coil: c_plunger_eject
    player_controlled_eject_event: sw_launch

virtual_platform_start_active_switches:
    s_trough1
    s_trough2
    s_trough3
    s_trough4
    s_trough5