#config_version=3

# Config file for Step 4 of our step-by-step tutorial.
# https://missionpinball.com/docs/tutorial/

# WARNING: The switch and coil numbers in this configuration file are for a Demolition Man machine.
# Do not use this file with your own hardware unless you change the coil and switch numbers to match your actual
# hardware!

switches:
    s_left_flipper:
        number: SF4
    s_right_flipper:
        number: SF2

coils:
    c_flipper_left_main: 
        number: FLLM
        pulse_ms: 25
    c_flipper_left_hold: 
        number: FLLH
    c_flipper_right_main: 
        number: FLRM
        pulse_ms: 25
    c_flipper_right_hold: 
        number: FLRH

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
        enable_events: machine_reset_phase_3
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
        enable_events: machine_reset_phase_3

dmd:
    physical: yes
    width: 128
    height: 32

window:
    elements:
      - type: virtualdmd
        width: 512
        height: 128
        h_pos: center
        v_pos: center
        pixel_color: ff6600
        dark_color: 220000
        pixel_spacing: 1
      - type: shape
        shape: box
        width: 516
        height: 132
        color: aaaaaa
        thickness: 2
      - type: text
        font: tall title
        text: MY AWESOME GAME
        h_pos: center
        v_pos: top
        y: 60
        size: 100
        antialias: yes
        layer: 1
        color: ee9900

slide_player:
    mode_attract_started:
        type: text
        text: PRESS START
        slide_priority: 10
        