#config_version=3

# Config file for Step 8 of our step-by-step tutorial.
# https://missionpinball.com/docs/tutorial/

# WARNING: The switch and coil numbers in this configuration file are for a Demolition Man machine.
# Do not use this file with your own hardware unless you change the coil and switch numbers to match your actual
# hardware!

switches:
    s_left_flipper:
        number: SF4
    s_right_flipper:
        number: SF2
    s_trough1:
        number: s31
        type: NC
    s_trough2:
        number: s32
        type: NC
    s_trough3:
        number: s33
        type: NC
    s_trough4:
        number: s34
        type: NC
    s_trough5:
        number: s35
        type: NC
    s_trough_jam:
        number: s36
        type: NC

coils:
    c_flipper_left_main: 
        number: FLLM
        pulse_ms: 25
    c_flipper_left_hold: 
        number: FLLH
    c_flipper_right_main: 
        number: FLRM
        pulse_ms: 25
    c_flipper_right_hold: 
        number: FLRH
    c_trough_eject:
        number: c01
        pulse_ms: 25

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
        enable_events: machine_reset_phase_3
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
        enable_events: machine_reset_phase_3

dmd:
    physical: yes
    width: 128
    height: 32

window:
    elements:
      - type: virtualdmd
        width: 512
        height: 128
        h_pos: center
        v_pos: center
        pixel_color: ff6600
        dark_color: 220000
        pixel_spacing: 1
      - type: shape
        shape: box
        width: 516
        height: 132
        color: aaaaaa
        thickness: 2
      - type: text
        font: tall title
        text: MY AWESOME GAME
        h_pos: center
        v_pos: top
        y: 60
        size: 100
        antialias: yes
        layer: 1
        color: ee9900

slide_player:
    attract_start:
        type: text
        text: PRESS START

keyboard:
    z:
        switch: s_left_flipper
    /:
        switch: s_right_flipper
    1:
        switch: s_trough1
        toggle: true
    2:
        switch: s_trough2
        toggle: true
    3:
        switch: s_trough3
        toggle: true
    4:
        switch: s_trough4
        toggle: true
    5:
        switch: s_trough5
        toggle: true

ball_devices:
  bd_trough:
    tags: trough, home, drain
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough_jam
    eject_coil: c_trough_eject
    entrance_count_delay: 300ms
    jam_switch: s_trough_jam
    debug: true

virtual_platform_start_active_switches:
    s_trough1
    s_trough2
    s_trough3
    s_trough4
    s_trough5