# config_version=3

# Skill shot mode
# One of the five standup targets is lit, sweeping back-and-forth at a 1s interval. Hit the lit
# standup for 200,000 points. Mode timer starts when the ball enters the playfield and stops 3s
# after that so the player only gets one shot.


mode:
    start_events: ball_starting
    stop_events: timer_mode_timer_complete, target_group_standups_hit
    priority: 300

timers:
    mode_timer:
        start_events: balldevice_playfield_ball_enter
        start_value: 3
        start_paused: yes
        end_value: 0
        direction: down
        tick_interval: 1s
        control_events:
          - event: balldevice_playfield_ball_enter
            action: start
    target_rotator:
        start_running: yes
        tick_interval: 1s

#slide_player:
#    mode_skillshot_started:
#      - type: text
#        text: "SKILLSHOT: LIT STANDUP"
#        decorators:
#            type: blink
#            repeats: -1
#            on_secs: .5
#            off_secs: .5
#        font: small
#        y: 1
#        shade: 0
#        layer: 1

shot_profiles:
    skill:
        rotation_pattern: r, r, r, r, l, l, l, l
        states:
            - name: unlit
              light_script: "off"
            - name: lit
              light_script: flash
              repeat: yes
              tocks_per_sec: 10
            - name: hit
              light_script: "on"

shots:
  standup_1:
    advance_events: mode_skillshot_started

shot_groups:
    standups:
        profile: skill
        rotate_events: timer_target_rotator_tick
        reset_events: mode_skillshot_started|1

scoring:
    standups_hit_me_active_hit:
        score: 200000
