# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coils.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='coils.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x63oils.proto\"N\n\x10PulseCoilRequest\x12\x13\n\x0b\x63oil_number\x18\x01 \x01(\t\x12\x10\n\x08pulse_ms\x18\x02 \x01(\r\x12\x13\n\x0bpulse_power\x18\x03 \x01(\x02\"c\n\x11\x45nableCoilRequest\x12\x13\n\x0b\x63oil_number\x18\x01 \x01(\t\x12\x10\n\x08pulse_ms\x18\x02 \x01(\r\x12\x13\n\x0bpulse_power\x18\x03 \x01(\x02\x12\x12\n\nhold_power\x18\x04 \x01(\x02\")\n\x12\x44isableCoilRequest\x12\x13\n\x0b\x63oil_number\x18\x01 \x01(\t\"\x85\x01\n\x1c\x43onfigureHardwareRuleRequest\x12\x13\n\x0b\x63oil_number\x18\x01 \x01(\t\x12\x15\n\rswitch_number\x18\x02 \x01(\t\x12\x10\n\x08pulse_ms\x18\x03 \x01(\r\x12\x13\n\x0bpulse_power\x18\x04 \x01(\x02\x12\x12\n\nhold_power\x18\x05 \x01(\x02\"\x0e\n\x0c\x43oilResponse\"G\n\x19RemoveHardwareRuleRequest\x12\x13\n\x0b\x63oil_number\x18\x01 \x01(\t\x12\x15\n\rswitch_number\x18\x02 \x01(\tb\x06proto3'
)




_PULSECOILREQUEST = _descriptor.Descriptor(
  name='PulseCoilRequest',
  full_name='PulseCoilRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='coil_number', full_name='PulseCoilRequest.coil_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pulse_ms', full_name='PulseCoilRequest.pulse_ms', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pulse_power', full_name='PulseCoilRequest.pulse_power', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=93,
)


_ENABLECOILREQUEST = _descriptor.Descriptor(
  name='EnableCoilRequest',
  full_name='EnableCoilRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='coil_number', full_name='EnableCoilRequest.coil_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pulse_ms', full_name='EnableCoilRequest.pulse_ms', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pulse_power', full_name='EnableCoilRequest.pulse_power', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hold_power', full_name='EnableCoilRequest.hold_power', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=194,
)


_DISABLECOILREQUEST = _descriptor.Descriptor(
  name='DisableCoilRequest',
  full_name='DisableCoilRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='coil_number', full_name='DisableCoilRequest.coil_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=237,
)


_CONFIGUREHARDWARERULEREQUEST = _descriptor.Descriptor(
  name='ConfigureHardwareRuleRequest',
  full_name='ConfigureHardwareRuleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='coil_number', full_name='ConfigureHardwareRuleRequest.coil_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='switch_number', full_name='ConfigureHardwareRuleRequest.switch_number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pulse_ms', full_name='ConfigureHardwareRuleRequest.pulse_ms', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pulse_power', full_name='ConfigureHardwareRuleRequest.pulse_power', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hold_power', full_name='ConfigureHardwareRuleRequest.hold_power', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=373,
)


_COILRESPONSE = _descriptor.Descriptor(
  name='CoilResponse',
  full_name='CoilResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=389,
)


_REMOVEHARDWARERULEREQUEST = _descriptor.Descriptor(
  name='RemoveHardwareRuleRequest',
  full_name='RemoveHardwareRuleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='coil_number', full_name='RemoveHardwareRuleRequest.coil_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='switch_number', full_name='RemoveHardwareRuleRequest.switch_number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=462,
)

DESCRIPTOR.message_types_by_name['PulseCoilRequest'] = _PULSECOILREQUEST
DESCRIPTOR.message_types_by_name['EnableCoilRequest'] = _ENABLECOILREQUEST
DESCRIPTOR.message_types_by_name['DisableCoilRequest'] = _DISABLECOILREQUEST
DESCRIPTOR.message_types_by_name['ConfigureHardwareRuleRequest'] = _CONFIGUREHARDWARERULEREQUEST
DESCRIPTOR.message_types_by_name['CoilResponse'] = _COILRESPONSE
DESCRIPTOR.message_types_by_name['RemoveHardwareRuleRequest'] = _REMOVEHARDWARERULEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PulseCoilRequest = _reflection.GeneratedProtocolMessageType('PulseCoilRequest', (_message.Message,), {
  'DESCRIPTOR' : _PULSECOILREQUEST,
  '__module__' : 'coils_pb2'
  # @@protoc_insertion_point(class_scope:PulseCoilRequest)
  })
_sym_db.RegisterMessage(PulseCoilRequest)

EnableCoilRequest = _reflection.GeneratedProtocolMessageType('EnableCoilRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENABLECOILREQUEST,
  '__module__' : 'coils_pb2'
  # @@protoc_insertion_point(class_scope:EnableCoilRequest)
  })
_sym_db.RegisterMessage(EnableCoilRequest)

DisableCoilRequest = _reflection.GeneratedProtocolMessageType('DisableCoilRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISABLECOILREQUEST,
  '__module__' : 'coils_pb2'
  # @@protoc_insertion_point(class_scope:DisableCoilRequest)
  })
_sym_db.RegisterMessage(DisableCoilRequest)

ConfigureHardwareRuleRequest = _reflection.GeneratedProtocolMessageType('ConfigureHardwareRuleRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGUREHARDWARERULEREQUEST,
  '__module__' : 'coils_pb2'
  # @@protoc_insertion_point(class_scope:ConfigureHardwareRuleRequest)
  })
_sym_db.RegisterMessage(ConfigureHardwareRuleRequest)

CoilResponse = _reflection.GeneratedProtocolMessageType('CoilResponse', (_message.Message,), {
  'DESCRIPTOR' : _COILRESPONSE,
  '__module__' : 'coils_pb2'
  # @@protoc_insertion_point(class_scope:CoilResponse)
  })
_sym_db.RegisterMessage(CoilResponse)

RemoveHardwareRuleRequest = _reflection.GeneratedProtocolMessageType('RemoveHardwareRuleRequest', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEHARDWARERULEREQUEST,
  '__module__' : 'coils_pb2'
  # @@protoc_insertion_point(class_scope:RemoveHardwareRuleRequest)
  })
_sym_db.RegisterMessage(RemoveHardwareRuleRequest)


# @@protoc_insertion_point(module_scope)
