# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import get_plaform_details_pb2 as get__plaform__details__pb2
from . import coils_pb2 as coils__pb2
from . import fade_light_pb2 as fade__light__pb2
from . import switch_pb2 as switch__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='platform.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eplatform.proto\x1a\x19get_plaform_details.proto\x1a\x0b\x63oils.proto\x1a\x10\x66\x61\x64\x65_light.proto\x1a\x0cswitch.proto2\xed\x03\n\x10HardwarePlatform\x12M\n\x12GetPlatformDetails\x12\x1a.GetPlatformDetailsRequest\x1a\x1b.GetPlatformDetailsResponse\x12;\n\x10GetSwitchChanges\x12\x15.SwitchChangesRequest\x1a\x0e.SwitchChanges0\x01\x12\x32\n\tLightFade\x12\x11.FadeLightRequest\x1a\x12.FadeLightResponse\x12-\n\tCoilPulse\x12\x11.PulseCoilRequest\x1a\r.CoilResponse\x12/\n\nCoilEnable\x12\x12.EnableCoilRequest\x1a\r.CoilResponse\x12\x31\n\x0b\x43oilDisable\x12\x13.DisableCoilRequest\x1a\r.CoilResponse\x12\x45\n\x15\x43onfigureHardwareRule\x12\x1d.ConfigureHardwareRuleRequest\x1a\r.CoilResponse\x12?\n\x12RemoveHardwareRule\x12\x1a.RemoveHardwareRuleRequest\x1a\r.CoilResponseb\x06proto3'
  ,
  dependencies=[get__plaform__details__pb2.DESCRIPTOR,coils__pb2.DESCRIPTOR,fade__light__pb2.DESCRIPTOR,switch__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_HARDWAREPLATFORM = _descriptor.ServiceDescriptor(
  name='HardwarePlatform',
  full_name='HardwarePlatform',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=91,
  serialized_end=584,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPlatformDetails',
    full_name='HardwarePlatform.GetPlatformDetails',
    index=0,
    containing_service=None,
    input_type=get__plaform__details__pb2._GETPLATFORMDETAILSREQUEST,
    output_type=get__plaform__details__pb2._GETPLATFORMDETAILSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSwitchChanges',
    full_name='HardwarePlatform.GetSwitchChanges',
    index=1,
    containing_service=None,
    input_type=switch__pb2._SWITCHCHANGESREQUEST,
    output_type=switch__pb2._SWITCHCHANGES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LightFade',
    full_name='HardwarePlatform.LightFade',
    index=2,
    containing_service=None,
    input_type=fade__light__pb2._FADELIGHTREQUEST,
    output_type=fade__light__pb2._FADELIGHTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CoilPulse',
    full_name='HardwarePlatform.CoilPulse',
    index=3,
    containing_service=None,
    input_type=coils__pb2._PULSECOILREQUEST,
    output_type=coils__pb2._COILRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CoilEnable',
    full_name='HardwarePlatform.CoilEnable',
    index=4,
    containing_service=None,
    input_type=coils__pb2._ENABLECOILREQUEST,
    output_type=coils__pb2._COILRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CoilDisable',
    full_name='HardwarePlatform.CoilDisable',
    index=5,
    containing_service=None,
    input_type=coils__pb2._DISABLECOILREQUEST,
    output_type=coils__pb2._COILRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ConfigureHardwareRule',
    full_name='HardwarePlatform.ConfigureHardwareRule',
    index=6,
    containing_service=None,
    input_type=coils__pb2._CONFIGUREHARDWARERULEREQUEST,
    output_type=coils__pb2._COILRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveHardwareRule',
    full_name='HardwarePlatform.RemoveHardwareRule',
    index=7,
    containing_service=None,
    input_type=coils__pb2._REMOVEHARDWARERULEREQUEST,
    output_type=coils__pb2._COILRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HARDWAREPLATFORM)

DESCRIPTOR.services_by_name['HardwarePlatform'] = _HARDWAREPLATFORM

# @@protoc_insertion_point(module_scope)
