#config_version=3

# Config file for Step 10 of our step-by-step tutorial.
# https://missionpinball.com/docs/tutorial/

# WARNING: This is for a Demolition Man machine controlled by a P-ROC. Do not
# use this file with your own hardware unless you change the coil and switch
# numbers to match your actual hardware!

game:
    player_controlled_eject_tag: launch

hardware:
    platform: p_roc
    driverboards: wpc

switches:
# Fliptronics
    s_right_flipper_eos:
        number: sf1
        tags:
        label:
    s_right_flipper:
        number: sf2
        tags: player
        label:
        tags: right_flipper
    s_left_flipper_eos:
        number: sf3
        tags:
        label:
    s_left_flipper:
        number: sf4
        tags: player
        label:
        tags: left_flipper
    s_flipper_upper_left_eos:
        number: sf5
        tags:
        label:
    s_flipper_upper_left:
        number: sf6
        tags: player
        label:
    s_flipper_upper_right_eos:
        number: sf7
        tags:
        label:
    s_flipper_upper_right:
        number: sf8
        tags: player
        label:

# Direct
    s_left_coin:
        number: sd1
        tags:
        label:
    s_center_coin:
        number: sd2
        tags:
        label:
    s_right_coin:
        number: sd3
        tags:
        label:
    s_fourth_coin:
        number: sd4
        tags:
        label:
    s_esc:
        number: sd5
        tags:
        label:
    s_down:
        number: sd6
        tags: volume_down
        label:
    s_up:
        number: sd7
        tags: volume_up
        label:
    s_enter:
        number: sd8
        tags:
        label:

# Matrix
    s_launch:
        number: s11
        label:
        tags: launch, player
    s_left_handle_button:
        number: s12
        label:
        tags: player
    s_start:
        number: s13
        label:
        tags: start, player
    s_plumb_bob:
        number: s14
        label:
        tags: tilt
    s_left_outlane:
        number: s15
        label:
        tags: playfield_active, outlane
    s_left_inlane:
        number: s16
        label:
        tags: playfield_active, inlane
    s_right_inlane:
        number: s17
        label:
        tags: playfield_active, inlane
    s_right_outlane:
        number: s18
        label:
        tags: playfield_active, outlane
    s_slam_tilt:
        number: s21
        label:
        tags: slamtilt
    s_coin_door_closed:
        number: s22
        label:
        tags:
    s_buy_in:
        number: s23
        label:
        tags:
    s_always_closed:
        number: s24
        label:
        tags:
    s_claw_position_1:
        number: s25
        label:
        tags:
        type: NC
    s_claw_position_2:
        number: s26
        label:
        tags:
        type: NC
    s_plunger_lane:
        number: s27
        label:
        tags:
    #name:
    #    number: s28
    #    label:
    #    tags:
    s_trough1:
        number: s31
        label:
        tags:
        type: NC
    s_trough2:
        number: s32
        label:
        tags:
        type: NC
    s_trough3:
        number: s33
        label:
        tags:
        type: NC
    s_trough4:
        number: s34
        label:
        tags:
        type: NC
    s_trough5:
        number: s35
        label:
        tags:
        type: NC
    s_trough_jam:
        number: s36
        label:
        tags:
        type: NC
    #name:
    #    number: s37
    #    label:
    #    tags:
    s_standup_5:
        number: s38
        label:
        tags: playfield_active
    s_left_slingshot:
        number: s41
        label:
        tags: playfield_active, slingshot
    s_right_slingshot:
        number: s42
        label:
        tags: playfield_active, slingshot
    s_left_jet:
        number: s43
        label:
        tags: playfield_active, jet
    s_top_slingshot:
        number: s44
        label:
        tags:  playfield_active, jet
    s_right_jet:
        number: s45
        label:
        tags:  playfield_active, jet
    s_right_ramp_enter:
        number: s46
        label:
        tags:  playfield_active, ramp_1_enter
    s_right_ramp_exit:
        number: s47
        label:
        tags:  playfield_active
    s_right_freeway:
        number: s48
        label:
        tags:  playfield_active
    s_left_ramp_enter:
        number: s51
        label:
        tags:  playfield_active, ramp_1_enter
    s_left_ramp_exit:
        number: s52
        label:
        tags:  playfield_active
    s_center_ramp:
        number: s53
        label:
        tags:  playfield_active
    s_upper_rebound:
        number: s54
        label:
        tags: playfield_active
    s_left_loop:
        number: s55
        label:
        tags: playfield_active
    s_standup_2:
        number: s56
        label:
        tags: playfield_active
    s_standup_3:
        number: s57
        label:
        tags: playfield_active
    s_standup_4:
        number: s58
        label:
        tags: playfield_active
    s_side_ramp_enter:
        number: s61
        label:
        tags: playfield_active, ramp_2_enter
    s_side_ramp_exit:
        number: s62
        label:
        tags: playfield_active
    s_left_rollover:
        number: s63
        label:
        tags: playfield_active
    s_center_rollover:
        number: s64
        label:
        tags: playfield_active
    s_right_rollover:
        number: s65
        label:
        tags: playfield_active
    s_eject:
        number: s66
        label:
        tags: playfield_active
    s_elevator_index:
        number: s67
        label:
        tags:
        type: NC
    #name:
    #    number: s68
    #    label:
    #    tags:
    s_car_chase_1:
        number: s71
        label:
        tags: playfield_active, small_car_crash
        type: NC
    s_car_chase_2:
        number: s72
        label:
        tags: playfield_active, big_car_crash
        type: NC
    s_top_popper:
        number: s73
        label:
        tags:
        type: NC
    s_elevator_hold:
        number: s74
        label:
        tags:
        type: NC
    #name:
    #    number: s75
    #    label:
    #    tags:
    s_bottom_popper:
        number: s76
        label:
        tags:
        type: NC
    s_eyeball_standup:
        number: s77
        label:
        tags: playfield_active
    s_standup_1:
        number: s78
        label:
        tags: playfield_active
    s_claw_capture_simon:
        number: s81
        label:
        tags: playfield_active
    s_claw_super_jets:
        number: s82
        label:
        tags: playfield_active
    s_claw_prison_break:
        number: s83
        label:
        tags: playfield_active
    s_claw_lock_freeze:
        number: s84
        label:
        tags: playfield_active
    s_claw_start_acmag:
        number: s85
        label:
        tags: playfield_active, acmag
    s_upper_left_flipper_gate:
        number: s86
        label:
        tags: playfield_active
    s_car_chase_standup:
        number: s87
        label:
        tags: playfield_active
    s_lower_rebound:
        number: s88
        label:
        tags: playfield_active

coils:
    c_trough_eject:
        number: c01
        label:
        tags:
        pulse_ms: 25
    c_bottom_popper:
        number: c02
        label:
        tags:
        pulse_ms: 25
    c_plunger_eject:
        number: c03
        label:
        tags:
        pulse_ms: 25
    c_top_popper:
        number: c04
        label:
        tags:
        pulse_ms: 30
    c_diverter_power:
        number: c05
        label:
        tags:
        holdPatter: 2-9
        pulse_ms: 30
    #name:
    #    number: c06
    #    label:
    #    tags:
    c_knocker:
        number: c07
        label:
        tags:
    #name:
    #    number: c08
    #    label:
    #    tags:
    c_left_slingshot:
        number: c09
        label:
        tags:
    c_right_slingshot:
        number: c10
        label:
        tags:
    c_left_jet_bumper:
        number: c11
        label:
        tags:
    c_top_slingshot:
        number: c12
        label:
        tags:
    c_right_jet_bumper:
        number: c13
        label:
        tags:
    c_retina_eject:
        number: c14
        label:
        tags:
    c_diverter_hold:
        number: c15
        label:
        tags:
        allow_enable: true
    #name:
    #    number: c16
    #    label:
    #    tags:
    c_elevator_motor:
        number: c18
        label:
        tags:
        allow_enable: true
    c_claw_motor_left:
        number: c19
        label:
        tags:
        allow_enable: true
    c_claw_motor_right:
        number: c20
        label:
        tags:
        allow_enable: true

# Fliptronics coils
    c_flipper_left_main:
        number: fllm
        label:
        tags:
        pulse_ms: 30
    c_flipper_left_hold:
        number: fllh
        label:
        tags:
    c_flipper_right_main:
        number: flrm
        label:
        tags:
        pulse_ms: 30
    c_flipper_right_hold:
        number: flrh
        label:
        tags:
    c_flipper_upper_main:
        number: fulm
        label:
        tags:
        pulse_ms: 30
    c_flipper_upper_hold:
        number: fulh
        label:
        tags:
    c_claw_magnet:
        number: furm
        label:
        tags:
        allow_enable: yes
    #name:
    #    number: furh
    #    label:
    #    tags:

matrix_lights:

    l_ball_save:
        number: l11
        label:
        tags:
    l_fortress_multiball:
        number: l12
        label:
        tags:
    l_museum_multiball:
        number: l13
        label:
        tags:
    l_cryoprison_multiball:
        number: l14
        label:
        tags:
    l_wasteland_multiball:
        number: l15
        label:
        tags:
    l_shoot_again:
        number: l16
        label:
        tags:
    l_access_claw:
        number: l17
        label:
        tags:
    l_left_ramp_explode:
        number: l18
        label:
        tags:
    l_right_ramp_jackpot:
        number: l21
        label:
        tags:
    l_right_loop_explode:
        number: l22
        label:
        tags:
    l_light_quick_freeze:
        number: l23
        label:
        tags:
    l_freeze_4:
        number: l24
        label:
        tags:
    l_claw_ready:
        number: l25
        label:
        tags:
    l_freeze_3:
        number: l26
        label:
        tags:
    l_freeze_2:
        number: l27
        label:
        tags:
    l_freeze_1:
        number: l28
        label:
        tags:
    l_right_loop_jackpot:
        number: l31
        label:
        tags:
    l_standup_5:
        number: l32
        label:
        tags:
    l_right_ramp_arrow:
        number: l33
        label:
        tags:
    l_left_ramp_jackpot:
        number: l34
        label:
        tags:
    l_left_loop_jackpot:
        number: l35
        label:
        tags:
    l_car_crash_top:
        number: l36
        label:
        tags:
    l_standup_1:
        number: l37
        label:
        tags:
    l_car_crash_center:
        number: l38
        label:
        tags:
    l_right_ramp_explode:
        number: l41
        label:
        tags:
    l_right_ramp_car_chase:
        number: l42
        label:
        tags:
    l_quick_freeze:
        number: l43
        label:
        tags:
    l_left_ramp_car_chase:
        number: l44
        label:
        tags:
    l_extra_ball:
        number: l45
        label:
        tags:
    l_start_multiball:
        number: l46
        label:
        tags:
    l_car_crash_bottom:
        number: l47
        label:
        tags:
    l_left_loop_explode:
        number: l48
        label:
        tags:
    l_underground_arrow:
        number: l51
        label:
        tags:
    l_underground_jackpot:
        number: l52
        label:
        tags:
    l_standup_2:
        number: l53
        label:
        tags:
    l_left_ramp_arrow:
        number: l54
        label:
        tags:
    l_side_ramp_jackpot:
        number: l55
        label:
        tags:
    l_side_ramp_arrow:
        number: l56
        label:
        tags:
    l_left_loop_arrow:
        number: l57
        label:
        tags:
    l_center_ramp_jackpot:
        number: l58
        label:
        tags:
    l_claw_capture_simon:
        number: l61
        label:
        tags:
    l_claw_super_jets:
        number: l62
        label:
        tags:
    l_claw_prison_break:
        number: l63
        label:
        tags:
    l_claw_lock_freeze:
        number: l64
        label:
        tags:
    l_claw_start_acmag:
        number: l65
        label:
        tags:
    l_left_rollover:
        number: l66
        label:
        tags:
    l_middle_rollover:
        number: l67
        label:
        tags:
    l_right_rollover:
        number: l68
        label:
        tags:
    l_super_jackpot:
        number: l71
        label:
        tags:
    l_computer:
        number: l72
        label:
        tags:
    l_demo_time:
        number: l73
        label:
        tags:
    #name:
    #    number: l74
    #    label:
    #    tags:
    #name:
    #    number: l75
    #    label:
    #    tags:
    l_standup_4:
        number: l76
        label:
        tags:
    l_standup_3:
        number: l77
        label:
        tags:
    l_retina_scan:
        number: l78
        label:
        tags:
    l_center_ramp_middle:
        number: l81
        label:
        tags:
    l_center_ramp_outer:
        number: l82
        label:
        tags:
    l_center_ramp_inner:
        number: l83
        label:
        tags:
    l_center_ramp_arrow:
        number: l84
        label:
        tags:
    l_right_loop_arrow:
        number: l85
        label:
        tags:
    l_buy_in:
        number: l86
        label:
        tags:
    l_ball_launch:
        number: l87
        label:
        tags:
    l_start:
        number: l88
        label:
        tags:

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper

dmd:
    physical: yes
    width: 128
    height: 32

window:
    elements:
      - type: virtualdmd
        width: 512
        height: 128
        h_pos: center
        v_pos: center
        pixel_color: ff6600
        dark_color: 220000
        pixel_spacing: 1
      - type: shape
        shape: box
        width: 516
        height: 132
        color: aaaaaa
        thickness: 2
      - type: text
        font: tall title
        text: MY AWESOME GAME
        h_pos: center
        v_pos: top
        y: 60
        size: 100
        antialias: yes
        layer: 1
        color: ee9900

slide_player:
    attract_start:
        type: text
        text: PRESS START
    ball_started:
        type: text
        text: PLAYER %player BALL %ball

keyboard:
    z:
        switch: s_left_flipper
    /:
        switch: s_right_flipper
    1:
        switch: s_trough1
        toggle: true
    2:
        switch: s_trough2
        toggle: true
    3:
        switch: s_trough3
        toggle: true
    4:
        switch: s_trough4
        toggle: true
    5:
        switch: s_trough5
        toggle: true
    p:
        switch: s_plunger_lane
        toggle: true
    s:
        switch: s_start
    L:
        switch: s_launch
    q:
        switch: s_right_inlane

ball_devices:
  bd_trough:
    tags: trough, home, drain
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough_jam
    eject_coil: c_trough_eject
    confirm_eject_type: target
    entrance_count_delay: 300ms
    jam_switch: s_trough_jam
    eject_targets: bd_plunger

  bd_plunger:
    ball_switches: s_plunger_lane
    entrance_count_delay: 300ms
    exit_count_delay: 3s
    eject_coil: c_plunger_eject
    confirm_eject_type: count
    tags: ball_add_live

  bd_retina_hole:
    ball_switches: s_eject
    eject_coil: c_retina_eject

  bd_lower_vuk:
    ball_switches: s_bottom_popper
    eject_coil: c_bottom_popper

  bd_upper_vuk:
    ball_switches: s_top_popper
    eject_coil: c_top_popper

  bd_elevator:
    ball_switches: s_elevator_hold

virtual_platform_start_active_switches:
    s_trough1
    s_trough2
    s_trough3
    s_trough4
    s_trough5

autofire_coils:
  left_slingshot:
    coil: c_left_slingshot
    switch: s_left_slingshot
  right_slingshot:
    coil: c_right_slingshot
    switch: s_right_slingshot
  upper_slingshot:
    coil: c_top_slingshot
    switch: s_top_slingshot
  left_jet:
    coil: c_left_jet_bumper
    switch: s_left_jet
  right_jet:
    coil: c_right_jet_bumper
    switch: s_right_jet