#config_version=3

# Config file for Step 5 of our step-by-step tutorial.
# https://missionpinball.com/docs/tutorial/

# WARNING: This is for a Demolition Man machine controlled by a P-ROC. Do not
# use this file with your own hardware unless you change the coil and switch
# numbers to match your actual hardware!

Hardware:
    Platform: p_roc
    DriverBoards: wpc

switches:
    s_left_flipper:
        number: SF4
    s_right_flipper:
        number: SF2

coils:
    c_flipper_left_main: 
        number: FLLM
        pulse_ms: 25
    c_flipper_left_hold: 
        number: FLLH
    c_flipper_right_main: 
        number: FLRM
        pulse_ms: 25
    c_flipper_right_hold: 
        number: FLRH

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
        enable_events: machine_reset_phase_3
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
        enable_events: machine_reset_phase_3