name: Wheel Builder

on:
  push:
    tags:
      - '*'

jobs:
  build_wheels:
    name: Push new release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mpf
    permissions:
      id-token: write

    steps:
      - name: Checkout MPF
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install MPF
        run: |
          sudo apt-get update
          sudo apt-get install -y '^libxcb.*-dev' libx11-xcb-dev libjpeg-dev
          sudo apt-get install -y qt6-base-dev
          pip install --upgrade pip setuptools wheel build
          pip install -e .

      - name: Run tests
        run: python -m unittest discover -s mpf/tests

      - name: Build wheel
        run: python -m build

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
